org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.13
minecraft_version=1.21.1
minecraft_version_range=1.21.1
neo_version=21.1.79
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=repair_amulet
mod_name=Repair Amulet
mod_license=MIT
mod_version=2.8.3
mod_group_id=com.lucab.repair_amulet
mod_authors=lucab
mod_description=Repair Amulets that repair items with different tiers

jei_version=19.21.0.247
curios_version=9.2.0+1.21.1