modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="repair_amulet"
version="1.0.0"
displayName="Repair Amulet"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="lucab, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.repair_amulet]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.repair_amulet]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration