modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="repair_amulet"
version="1.4"
displayName="Repair Amulet"
displayURL="https://github.com/LcBert/Repair-Amulet-Mod"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="lucab"
description="Repair amulet with different tier"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.repair_amulet]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.repair_amulet]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.repair_amulet]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration